apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
        - name: hello
          image: hilel14/hello:{{ .Values.appVersion }}
          args: ["/opt/hilel14/target/hello-{{ .Values.appVersion }}.jar"]
      restartPolicy: Never
  backoffLimit: 0
