# This workflow will build a package using Maven, create a Docker image and then publish it to Docker Hub

name: Publish Docker Image
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Build
        run: mvn --batch-mode package
