# This workflow will build a package using Maven, create a Docker image and then publish it to Docker Hub

name: Publish Docker Image
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        # https://github.com/actions/setup-java#supported-version-syntax        
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: src/scripts/increment-version.sh
      - run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)